{% set name = "qdldl" %}
{% set version = "0.1.5.post3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 69c092f6e1fc23fb779a80a62e6fcdfe2eba05c925860248c4d6754f4736938f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  script_env:
    - CMAKE_GENERATOR='Visual Studio 16 2019' # [win]
    - CMAKE_GENERATOR_PLATFORM='x64' # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - numpy >=1.7
    - pip
    - python
    - pybind11
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy >=0.13.2

about:
  home: "https://github.com/oxfordcontrol/qdldl-python/"
  license: Apache 2.0
  license_family: APACHE
  summary: "QDLDL, a free LDL factorization routine."
