{% set name = "qdldl" %}
{% set version = "0.1.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f346a114c8342ee6d4dbd6471eef314199fb268d3bf7b95885ca351fde2b023f

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  script_env:
    - CMAKE_GENERATOR='Visual Studio 16 2019' # [win]
    - CMAKE_GENERATOR='Ninja' # [not win]
    - CMAKE_GENERATOR_PLATFORM='x64' # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja # [not win]
  host:
    - numpy
    - pip
    - python
    - pybind11
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy >=0.13.2

about:
  home: "https://github.com/oxfordcontrol/qdldl-python/"
  license: Apache 2.0
  license_family: APACHE
  summary: "QDLDL, a free LDL factorization routine."
